### ISSUE TITLE
VastBindAdapter的getItemViewType添加资源id鉴别方法

### ISSUE THREAD

**Issue by SakurajimaMaii** [SakurajimaMaii/VastUtils#40]
在之前的设计中，如果不加以判断，很容易产生下列报错：

```java
// 当你的getVBAdpItemType方法返回值被错误的设置为0，而你没察觉到时
android.content.res.Resources$NotFoundException: Resource ID #0x0
    at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:279)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2310)
    at android.content.res.Resources.getLayout(Resources.java:1293)
    .......
```

**Comment by SakurajimaMaii** [comment]
加入资源判断以及自定义异常
```kotlin
final override fun getItemViewType(position: Int):Int {
    val viewType = dataSource[position].getVBAdpItemType()
    try {
        // Identify whether there is a resource file for the resource id.
        Resources.getSystem().getLayout(viewType)
    }catch(e:Resources.NotFoundException){
        throw RuntimeException("Please check if the return value of the getVBAdpItemType method in ${dataSource[position].javaClass.simpleName}.kt is correct.")
    }
    return viewType
}
```
这是如果资源出错则会显示如下报错
```java
java.lang.RuntimeException: Please check if the return value of the getVBAdpItemType method in Person.kt is correct.
       at com.gcode.vastadapter.base.VastBindAdapter.getItemViewType(VastBindAdapter.kt:88)
       .....
```
加入了提示方便你更快找到出错点 `Person.kt`

**Comment by SakurajimaMaii** [comment]
在上次提交中Resources获取有问题，不应该是`Resources.getSystem()`,应该通过`mContext.resources`获取
```kotlin
final override fun getItemViewType(position: Int):Int {
    val viewType = dataSource[position].getVBAdpItemType()
    try {
        // Identify whether there is a resource file for the resource id.
        mContext.resources.getLayout(viewType)
    }catch(e:Resources.NotFoundException){
        throw RuntimeException("Please check if the return value of the getVBAdpItemType in ${dataSource[position].javaClass.simpleName}.kt is correct.")
    }
    return viewType
}
```
